In [13]:
import pandas as pd
import yfinance as yf
import numpy as np

In [14]:

ticker = "BTC-USD"
data = yf.download(tickers=ticker, period="5d", interval="5m")

[*********************100%***********************]  1 of 1 completed

In [15]:
close_list = data["Close"]["BTC-USD"].tolist()
open_list = data["Open"]["BTC-USD"].tolist()

In [16]:
zip(open_list, close_list)

In [17]:
data

Price,Close,High,Low,Open,Volume
Ticker,BTC-USD,BTC-USD,BTC-USD,BTC-USD,BTC-USD
Datetime,,,,,
2026-03-11 00:00:00+00:00,69861.562500,69956.929688,69844.687500,69956.929688,0
2026-03-11 00:05:00+00:00,69929.656250,69929.656250,69780.265625,69780.265625,32067584
2026-03-11 00:10:00+00:00,70063.679688,70063.679688,69922.421875,69989.062500,0
2026-03-11 00:15:00+00:00,69895.687500,70070.890625,69895.687500,70070.890625,49557504
2026-03-11 00:20:00+00:00,70032.898438,70036.601562,69990.585938,70036.601562,38776832
...,...,...,...,...,...
2026-03-15 09:30:00+00:00,71838.234375,71838.234375,71835.890625,71835.890625,0
2026-03-15 09:35:00+00:00,71821.445312,71847.906250,71808.281250,71847.906250,3203072
2026-03-15 09:40:00+00:00,71758.617188,71839.710938,71758.617188,71839.710938,149667840
2026-03-15 09:45:00+00:00,71734.296875,71769.242188,71734.296875,71760.195312,4487168
2026-03-15 09:50:00+00:00,71723.515625,71723.515625,71723.515625,71723.515625,0

In [1]:
from data_pipeline import load_bitget_btcusdt_5m

dft = load_bitget_btcusdt_5m()
dft

,timestamp,open,high,low,close,base_volume,quote_volume
0,2026-03-13 23:45:00+00:00,70913.7,70964.2,70874.0,70900.0,238.3908,1.690850e+07
1,2026-03-14 00:00:00+00:00,70900.0,70900.0,70713.3,70866.9,302.8395,2.144095e+07
2,2026-03-14 00:15:00+00:00,70866.9,70931.1,70755.0,70891.3,227.3918,1.610949e+07
3,2026-03-14 00:30:00+00:00,70891.3,70902.6,70535.0,70547.1,480.0404,3.395245e+07
4,2026-03-14 00:45:00+00:00,70547.1,70689.5,70530.0,70605.1,423.0225,2.986645e+07
...,...,...,...,...,...,...,...
315,2026-03-17 06:30:00+00:00,74187.9,74250.0,73948.7,73975.8,445.2708,3.300282e+07
316,2026-03-17 06:45:00+00:00,73975.8,74067.1,73927.7,74056.1,880.8964,6.518097e+07
317,2026-03-17 07:00:00+00:00,74056.1,74331.5,74034.2,74293.7,324.1364,2.405685e+07
318,2026-03-17 07:15:00+00:00,74293.7,74430.6,74285.8,74370.2,435.0313,3.234718e+07
319,2026-03-17 07:30:00+00:00,74370.2,74370.6,74294.0,74304.4,95.7351,7.116024e+06