In [1]:
import pandas as pd
import yfinance as yf
import numpy as np

In [2]:

ticker = "BTC-USD"
data = yf.download(tickers=ticker, period="5d", interval="5m")

[*********************100%***********************]  1 of 1 completed

In [3]:
close_list = data["Close"]["BTC-USD"].tolist()
open_list = data["Open"]["BTC-USD"].tolist()

In [4]:
zip(open_list, close_list)

In [5]:
data

Price,Close,High,Low,Open,Volume
Ticker,BTC-USD,BTC-USD,BTC-USD,BTC-USD,BTC-USD
Datetime,,,,,
2026-03-13 00:00:00+00:00,70426.640625,70446.867188,70426.640625,70446.867188,0
2026-03-13 00:05:00+00:00,70577.703125,70617.789062,70491.648438,70491.648438,196313088
2026-03-13 00:10:00+00:00,70949.187500,70949.187500,70738.781250,70738.781250,0
2026-03-13 00:15:00+00:00,71329.625000,71505.453125,71084.046875,71084.046875,316235776
2026-03-13 00:20:00+00:00,71639.507812,71691.476562,71283.437500,71283.437500,0
...,...,...,...,...,...
2026-03-17 11:00:00+00:00,73728.734375,73736.875000,73728.734375,73736.875000,0
2026-03-17 11:05:00+00:00,73890.460938,73891.484375,73785.671875,73785.671875,9015296
2026-03-17 11:10:00+00:00,73927.375000,73946.625000,73927.375000,73946.625000,1295704064
2026-03-17 11:15:00+00:00,73959.031250,73959.031250,73926.164062,73926.164062,83808256
2026-03-17 11:20:00+00:00,73968.054688,74003.195312,73946.492188,73946.492188,14532608

In [7]:
from data_pipeline import load_bitget_btcusdt_5m

dft = load_bitget_btcusdt_5m(130)
dft

,timestamp,open,high,low,close,base_volume,quote_volume
0,2026-03-17 00:40:00+00:00,74961.9,75050.7,74871.8,74953.3,147.8661,1.108149e+07
1,2026-03-17 00:45:00+00:00,74953.3,75079.0,74943.5,74977.1,85.8440,6.439077e+06
2,2026-03-17 00:50:00+00:00,74977.1,75011.6,74874.4,74992.8,88.6022,6.639675e+06
3,2026-03-17 00:55:00+00:00,74992.8,75280.0,74926.1,75280.0,150.1190,1.127760e+07
4,2026-03-17 01:00:00+00:00,75280.0,75386.5,75054.6,75092.9,344.0017,2.588994e+07
...,...,...,...,...,...,...,...
125,2026-03-17 11:05:00+00:00,73770.0,73909.9,73769.9,73892.8,264.8634,1.956183e+07
126,2026-03-17 11:10:00+00:00,73892.8,73954.8,73859.1,73898.2,168.7524,1.247122e+07
127,2026-03-17 11:15:00+00:00,73898.2,73970.0,73844.1,73970.0,162.1573,1.198646e+07
128,2026-03-17 11:20:00+00:00,73970.0,73979.7,73874.2,73944.1,90.3008,6.676331e+06
129,2026-03-17 11:25:00+00:00,73944.1,73951.6,73944.1,73951.6,0.4566,3.376579e+04